version: '3.8'

services:
  mining-frontend:
    image: ghcr.io/muqy1818/mining-safety-db-frontend:latest
    container_name: mining-frontend
    restart: unless-stopped
    ports:
      - "3000:80"  # 映射到3000端口，避免与其他服务冲突
    environment:
      - TZ=Asia/Shanghai
      # 后端API地址配置
      - REACT_APP_API_BASE_URL=https://mining-backend.ziven.site/api
      # AI功能开关（通过后端提供）
      - REACT_APP_ENABLE_AI_CHAT=true
      - REACT_APP_AI_STREAM_ENABLED=true
      # 反馈功能开关
      - REACT_APP_ENABLE_FEEDBACK=true
    networks:
      - mining-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mining-frontend.rule=Host(`mining-frontend.local`)"
      - "traefik.http.services.mining-frontend.loadbalancer.server.port=80"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mining-logs:/var/log/nginx

networks:
  mining-network:
    driver: bridge

volumes:
  mining-logs:
    driver: local